### ISSUE TITLE
[BUG] `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by sqrter** [thermoweb/jasypt-encrypt-plugin#17]
**Describe the bug**
I'm experiencing the IDE error:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.thermoweb.intellij.plugin.encrypt.actions.EncryptStringAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.github.thermoweb.encryptstringplugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)

```

**To Reproduce**
1. Install the plugin
2. Right-click on any opened editor

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 
 - Version 14.7 (23H124)
- WebStorm 2024.2.2 Build #WS-242.22855.79, built on September 18, 2024

**Comment by thermoweb** [comment]
Hi,

Thanks to report this. I'm already working on fixing this, I'm testing it on the beta branch.
I'll notify you when it's released on the main branch.

**Comment by sqrter** [comment]
Great, thanks! I'll install the update and test it once it's available on the marketplace
